#!/usr/bin/php
<?php
$collection = [];

api_collect("http://10.201.87.201/ptp/proxy/QmdoX2kxj863SG4m7VVPk21a26XzX8U2nCQXk6MUZ57GQu/GetWorkerStatus");
api_collect("http://10.201.87.202/ptp/proxy/QmYdvMgZDchUqahvnj5d75Gu6PjSBfzFfe9tEzCtovDtiX/GetWorkerStatus");

file_put_contents('/tmp/api_cache.json.new', json_encode($collection));
rename('/tmp/api_cache.json.new', '/tmp/api_cache.json');

function api_collect($url) {
        $data = file_get_contents($url);
        $json = json_decode($data, true);
        if ($json === null && json_last_error() !== JSON_ERROR_NONE) {
                echo "incorrect data";
        }

        foreach ($json['data']['workerStates'] as $worker) {
                $workerTmp = json_decode($worker['minerInfoJson'], true);
                $worker['minerInfoJson'] = $workerTmp;

                if (empty($worker['paraBlockDispatchedTo'])) {
                        $worker['paraBlockDispatchedTo'] = 'none';
                }

                $GLOBALS['collection'][$worker['worker']['name']] = [
                        'status'        => $worker['status'],
                        'synced_to'     => $worker['paraBlockDispatchedTo']
                ];
                if (!empty($worker['minerInfoJson']['raw']['state'])) {
                        $GLOBALS['collection'][$worker['worker']['name']]['state'] = $worker['minerInfoJson']['raw']['state'];
                } else {
                        $GLOBALS['collection'][$worker['worker']['name']]['state'] = 'S_SYNCING';
                }
        }
}

?>

