#!/bin/bash
for rack in 01 02 03 04
  do
    for pos in {01..22}
      do
        for side in L R
          do
            echo  R${rack}P${pos}${side};

        done
      done

      for pos in {25..45}
        do
          for side in L R
            do
              echo  R${rack}P${pos}${side};
          done
      done
done

for rack in 07 08 09 10
  do
    for pos in {01..22}
      do
        for side in L R
          do
            echo  R${rack}P${pos}${side};

        done
      done

      for pos in {25..46}
        do
          for side in L R
            do
              echo  R${rack}P${pos}${side};
          done
      done
done


for rack in 05 06
  do
    for pos in {01..24}
      do
        for side in L R
          do
            echo  R${rack}P${pos}${side};

        done
      done

done

